version: 2
jobs:
  build:
    docker:
      - image: REPLACE-ME-WITH-DOCKER-IMAGE

    steps:
      - checkout

      - run:
          name: install dependencies
          command: bundle install

      - run:
          name: build the jekyll site
          command: REPLACE-ME-WITH-BUILD-COMMAND

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
